// The catalog is generated by scripts/sync-settings.js from the upstream
// JSON Schema and committed to catalog/settings.json. We bundle it into
// the frontend at build time — it's static reference data, not user input,
// so going through a Tauri command would be ceremony for no benefit.

import raw from "../../catalog/settings.json";

export interface CatalogEntry {
  key: string;
  type?: string;
  description?: string;
  enum?: unknown[];
  examples?: unknown[];
  default?: unknown;
  /** May appear on array-typed entries; describes element schema. */
  items?: unknown;
  /** Open-ended — the schema sometimes carries fields we don't model yet. */
  [extra: string]: unknown;
}

interface CatalogFile {
  source: string;
  schemaId: string;
  fetchedAt: string;
  count: number;
  settings: CatalogEntry[];
}

const data = raw as CatalogFile;

/**
 * Skip catalog entries that are *containers* — object-typed parents whose
 * children are also catalog entries (e.g. `permissions` exists alongside
 * `permissions.defaultMode`). Containers aren't directly settable, so they
 * shouldn't appear as rows. Object-typed entries with no flattened
 * children stay (e.g. `env`, where the keys are user-defined).
 */
function isContainer(entry: CatalogEntry, all: CatalogEntry[]): boolean {
  if (entry.type !== "object") return false;
  const prefix = `${entry.key}.`;
  return all.some((other) => other.key.startsWith(prefix));
}

const FULL: CatalogEntry[] = data.settings;
const LEAF: CatalogEntry[] = FULL.filter((e) => !isContainer(e, FULL));
const BY_KEY: Map<string, CatalogEntry> = new Map(LEAF.map((e) => [e.key, e]));

/** Settable catalog entries (containers filtered out). */
export const CATALOG: ReadonlyArray<CatalogEntry> = LEAF;

export const CATALOG_META = {
  source: data.source,
  fetchedAt: data.fetchedAt,
  totalEntries: data.count,
  leafCount: LEAF.length,
} as const;

/** Lookup by exact dot-path. Walks up to find the closest parent on miss. */
export function findCatalogEntry(keyPath: string): CatalogEntry | null {
  const exact = BY_KEY.get(keyPath);
  if (exact) return exact;

  // Fallback: the user set a deeper path than the catalog tracks (e.g.
  // `env.ANTHROPIC_MODEL` under the catalog's top-level `env` object).
  // The closest parent's description is more useful than nothing.
  let trimmed = keyPath;
  while (trimmed.includes(".")) {
    trimmed = trimmed.slice(0, trimmed.lastIndexOf("."));
    const hit = FULL.find((e) => e.key === trimmed);
    if (hit) return hit;
  }
  return null;
}
